# restclient: https://github.com/Huachao/vscode-restclient

# @name: get welcome to API
GET http://localhost:3000/


###

# @name: get-api-gemini-status
GET http://localhost:3000/ping

###

# @name: create-lesson
POST http://localhost:3000/generate-lesson
Content-Type: application/json

{
    "subject": "Matemática",
    "grade_level": "7",
    "topic": "Frações e decimais"
}
