# restclient: https://github.com/Huachao/vscode-restclient

# @name: get welcome to API
GET https://pibiotecai.onrender.com/


###

# @name: get-api-gemini-status
GET https://pibiotecai.onrender.com/api/gemini/ping

###

# @name: create-lesson - Gemini
# @description: This endpoint generates a lesson plan based on the provided subject, grade level, and topic.
POST https://pibiotecai.onrender.com/api/gemini/generate
Content-Type: application/json

{
  "promptType": "lesson_plan",
  "data": {
    "subject": "Science",
    "grade_level": "8th Grade",
    "topic": "Photosynthesis"
  }
}

###

### @name: create-technical-report - Gemini
# @description: This endpoint generates a technical report based on the provided title, author, and date.
POST https://pibiotecai.onrender.com/api/gemini/generate
Content-Type: application/json

{
  "promptType": "technical_report",
  "data": {
    "title": "Revisão de desempenho do sistema",
    "author": "AI Team",
    "date": "2025-05-27"
  }
}

###

# @name: get-api-llama-status
GET https://pibiotecai.onrender.com/api/llama/ping

###

# @name: create-lesson - Llama
# @description: This endpoint generates a lesson plan based on the provided subject, grade level, and topic.

POST https://pibiotecai.onrender.com/api/llama/generate
Content-Type: application/json

{
  "promptType": "lesson_plan",
  "data": {
    "subject": "Science",
    "grade_level": "8th Grade",
    "topic": "Photosynthesis"
  }
}