# restclient: https://github.com/Huachao/vscode-restclient

# @name: get welcome to API
GET http://localhost:3000/


###

# @name: get-api-gemini-status
GET http://localhost:3000/api/gemini/ping

###

# @name: create-lesson - Gemini
# @description: This endpoint generates a lesson plan based on the provided subject, grade level, and topic.
POST http://localhost:3000/api/gemini/generate-lesson
Content-Type: application/json

{
    "subject": "Matemática",
    "grade_level": "7",
    "topic": "Frações e decimais"
}
